apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    env:
      - name: DEBUG
        value: "True"
      - name: SECRET_KEY
        value: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
      - name: ALLOWED_HOSTS
        value: "*"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    env:
      - name: DEBUG
        value: "True"
      - name: SECRET_KEY
        value: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
      - name: ALLOWED_HOSTS
        value: "*"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
